# -*- coding: utf-8 -*-
"""algo_sem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_nYW4c2DzDu0VLNB6CyWkWT2eXXgbxnK
"""

def selection_sort(arr): # spacial O(1), time O(n^2)
    n = len(arr)
    for i in range(n - 1):
        min = arr[i]
        min_i = i
        for j in range(i+1, n):
            if arr[j] < min:
                min_i = j
                min = arr[j]

        temp = arr[i]
        arr[i] = arr[min_i]
        arr[min_i] = temp
        #print(arr)

arr = [7, 3, 9, 4, 2, 5, 6, 1, 8]
selection_sort(arr) # 7 switches; (7+1)*7/2 = 28
arr2 = [3, 5, 2, 9, 8, 1, 6, 4, 7]
print("")
selection_sort(arr2) # 8 switches; (7+1)*7/2 = 28

import numpy as np
from timeit import default_timer as timer
import matplotlib.pyplot as plt

def random_sample(n):
    return [int(i) for i in np.random.randint(n, size=n)]

def reversed_sample(n):
    return list(range(n)[::-1])

def almost_sorted_sample(n):
    sample = list(range(1, n + 1))
    sample[n//2] = 0
    return sample

def half_zero_sample(n):
    return [0]*(n//2) + random_sample(n - n//2)

def slightly_scuffed_sample(n):
    return [int(i) for i in (np.arange(n) + np.random.randint(10, size=n))]

def test(sorting_function):
    ns = [100, 500, 1000, 2000, 4000, 6000, 8000, 10000]
    sample_types = [random_sample, reversed_sample, almost_sorted_sample, half_zero_sample, slightly_scuffed_sample]
    for sample_function in sample_types:
        ts = []
        for n in ns:
            sample1 = sample_function(n)
            sample2 = sample_function(n)
            sample3 = sample_function(n)
            start = timer()
            sorting_function(sample1)
            sorting_function(sample2)
            sorting_function(sample3)
            stop = timer()
            ts.append((stop - start)/3)

        plt.figure(figsize=(3, 3))
        plt.plot(ns, ts)
        plt.title(sample_function.__name__)
        plt.show()

test(selection_sort)

def selection_sort_dual(arr):
    i = 0
    j = len(arr) - 1
    while(i < j):
        min = arr[i]
        max = arr[i]
        min_i = i
        max_i = i
        for k in range(i, j + 1, 1):
            if (arr[k] > max):
                max = arr[k]
                max_i = k
            elif (arr[k] < min):
                min = arr[k]
                min_i = k

        temp = arr[i]
        arr[i] = arr[min_i]
        arr[min_i] = temp

        if (arr[min_i] == max):
            temp = arr[j]
            arr[j] = arr[min_i]
            arr[min_i] = temp
        else:
            temp = arr[j]
            arr[j] = arr[max_i]
            arr[max_i] = temp

        i += 1
        j -= 1

arr = [7, 3, 9, 4, 2, 5, 6, 1, 8]
selection_sort_dual(arr)
arr

test(selection_sort_dual)